 - name: Enablement of the EPEL repository (Internet need)
   yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
   when: ansible_os_family == "RedHat"
