 - name: Installation of ntp
   apt: name=ntp state=installed
   when: ansible_os_family == "Debian"
 - name: Installation of ntp Centos
   yum: name=ntp state=installed
   when: ansible_os_family == "RedHat"
 - name: Start NTP service
   service: name=ntpd state=restarted enabled=yes
