 - name: Install libselinux-python
   yum: name=libselinux-python state=installed
   when: ansible_os_family == "RedHat"
 - name: SELinux disable - CentOS
   selinux: state=disabled
   when: ansible_os_family == "RedHat"

