- name: Create the network configuration file for bridge devices
  template: src=bridge_{{ ansible_os_family }}.j2 dest=/etc/network/interfaces.d/{{ item.device }}.cfg
  with_items: network_bridge_interfaces
  when: network_bridge_interfaces is defined 
  register: bridge_result
