- name: "Install cloudstack agent Debian"
   apt: name=cloudstack-agent state=installed
  when: ansible_os_family == "Debian"
- name: "Install cloudstack agent CentOS"
   yum: name=cloudstack-agent state=installed
  when: ansible_os_family == "RedHat"

